//! Identifier newtypes for domain entities.
//!
//! Each identifier wraps an opaque string. New identifiers generated by this
//! module use ULID format (26-character Crockford base-32). Identifiers
//! received from external sources (deserialized JSON, database rows) are not
//! validated against ULID format — use [`is_valid_ulid`] or the `TryFrom`
//! impl when you need format guarantees at a trust boundary.

use serde::{Deserialize, Serialize};

/// Returns `true` if `s` is a valid ULID string (26 chars, `[0-9A-Z]`).
pub fn is_valid_ulid(s: &str) -> bool {
    s.len() == 26 && s.chars().all(|c| matches!(c, '0'..='9' | 'A'..='Z'))
}

/// Error returned when a string cannot be used as a ULID-format identifier.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("invalid identifier: must be 26 uppercase alphanumeric characters (ULID format)")]
pub struct InvalidIdentifier;

/// Macro for creating string identifier newtypes.
///
/// Generated identifiers from [`new()`] always use ULID format. Deserialization
/// and struct-literal construction accept any string (needed for tests and
/// legacy data). Use `TryFrom<String>` when ULID format must be enforced.
macro_rules! id_newtype {
    ($name:ident) => {
        #[doc = concat!("Opaque string identifier for ", stringify!($name), " entities.")]
        #[doc = ""]
        #[doc = "Values produced by [`Self::new()`] are ULID-format (26 chars, `[0-9A-Z]`)."]
        #[doc = "Values received via deserialization are not validated — use"]
        #[doc = "`TryFrom<String>` when ULID format must be enforced at a trust boundary."]
        #[derive(
            Debug,
            Clone,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            Serialize,
            Deserialize,
            schemars::JsonSchema,
        )]
        pub struct $name(pub String);

        impl $name {
            /// Generate a new identifier using a ULID.
            pub fn new() -> Self {
                Self(ulid::Ulid::new().to_string())
            }

            /// Get a string reference to the identifier.
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl TryFrom<String> for $name {
            type Error = InvalidIdentifier;

            /// Construct from a string, returning [`InvalidIdentifier`] if the
            /// string does not match ULID format (26 chars, `[0-9A-Z]`).
            fn try_from(s: String) -> Result<Self, Self::Error> {
                if crate::model::identifiers::is_valid_ulid(&s) {
                    Ok(Self(s))
                } else {
                    Err(InvalidIdentifier)
                }
            }
        }

        impl TryFrom<&str> for $name {
            type Error = InvalidIdentifier;

            fn try_from(s: &str) -> Result<Self, Self::Error> {
                Self::try_from(s.to_owned())
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }
    };
}

id_newtype!(RouteId);
id_newtype!(UpstreamId);
id_newtype!(PolicyId);
id_newtype!(PresetId);
id_newtype!(MutationId);

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::disallowed_methods)]
// reason: test-only code; panics are the correct failure mode in tests
mod tests {
    use super::*;

    #[test]
    fn ulid_format() {
        let id = RouteId::new();
        let s = &id.0;
        assert_eq!(s.len(), 26, "ULID should be 26 characters");
        assert!(
            s.chars().all(|c| c.is_ascii_alphanumeric()),
            "ULID should contain only ASCII alphanumeric characters"
        );
        // Verify all characters are in the base32 alphabet [0-9A-Z]
        assert!(
            s.chars().all(|c| matches!(c, '0'..='9' | 'A'..='Z')),
            "ULID should match [0-9A-Z]{{26}}"
        );
    }

    #[test]
    fn route_id_new_creates_unique_ids() {
        let id1 = RouteId::new();
        let id2 = RouteId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn upstream_id_serialization() -> Result<(), Box<dyn std::error::Error>> {
        let id = UpstreamId::new();
        let json = serde_json::to_string(&id)?;
        let deserialized: UpstreamId = serde_json::from_str(&json)?;
        assert_eq!(id, deserialized);
        Ok(())
    }

    #[test]
    fn id_as_str_returns_reference() {
        let id = PolicyId::new();
        let s = id.as_str();
        assert_eq!(s, &id.0);
        assert_eq!(s.len(), 26);
    }

    #[test]
    fn id_default_creates_new() {
        let id1 = PresetId::default();
        let id2 = PresetId::default();
        assert_ne!(id1, id2);
    }

    #[test]
    fn id_display_impl() {
        let id = MutationId::new();
        let displayed = format!("{id}");
        assert_eq!(displayed, id.0);
    }

    #[test]
    fn try_from_valid_ulid_succeeds() {
        let id = RouteId::new();
        let s = id.0.as_str();
        let result = RouteId::try_from(s);
        assert!(result.is_ok(), "valid ULID must be accepted");
        assert_eq!(result.unwrap().0, s);
    }

    #[test]
    fn try_from_invalid_string_fails() {
        let err = RouteId::try_from("route-1".to_owned());
        assert!(err.is_err(), "non-ULID string must be rejected");

        let err2 = UpstreamId::try_from("too-short".to_owned());
        assert!(err2.is_err(), "short string must be rejected");

        // lowercase letters are not valid ULID format
        let err3 = PolicyId::try_from("01arZ3NDEKTSV4RRFFQ69G5FAV".to_owned());
        assert!(err3.is_err(), "lowercase chars must be rejected");
    }

    #[test]
    fn is_valid_ulid_fn() {
        let id = RouteId::new();
        assert!(super::is_valid_ulid(&id.0));
        assert!(!super::is_valid_ulid("not-a-ulid"));
        assert!(!super::is_valid_ulid("")); // too short
    }
}
